[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 4321
  publish = "dist"
  autoLaunch = false
  framework = "astro"

[[redirects]]
  from = "/test-ssr-netlify-rewrite"
  to = "/revalidation"
  status = 200
  force = true

[[redirects]]
  from = "/test-ssg-netlify-rewrite"
  to = "/image-cdn"
  status = 200
  force = true
