[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "astro dev"
  port = 8888
  targetPort = 4321
  publish = "dist"
  autoLaunch = false
  framework = "astro"

[[redirects]]
  from = "/old-url"
  to = "/revalidation"
  status = 200
  force = true

  